### ISSUE TITLE
Map not in correct position

### ISSUE THREAD

**Issue by nlhkabu** [djangocon/2013.djangocon.eu#15]
Found this whilst browsing the site: 
![screenshot from 2015-02-01 13 41 55](https://cloud.githubusercontent.com/assets/3323703/5990803/5564cc08-aa18-11e4-90de-ca0f6a477d77.png)
I am using Firefox 35.0 on Fedora 20

**Comment by oinopion** [comment]
Hi @nlhkabu, this is not right repository, as this site for DjangoCon Europe _2013_. 2015 repo is here: https://github.com/evildmp/djangocon_europe
