### ISSUE TITLE
Paragraph breaks in proposal summaries

### ISSUE THREAD

**Issue by evildmp** [djangocon/2013.djangocon.eu#5]
Not all the proposals' paragraph breaks are showing at http://2013.djangocon.eu/vote/ - I think the ones that used plain text instead of markdown are coming out as single paragraphs, making them harder to read.

Not sure how this should be addressed

**Comment by olasitarska** [comment]
We think django-import-export broke something. @oinopion and @asendecka are already fixing that -- unfortunatelly, manually :(
